title: Madeline Shi
logo: "/profile%20photo.JPG"

description: |
  <p>
    Contact:
    <a href="mailto:mashi@davidson.edu">mashi@davidson.edu</a>
    <br>
    <span style="display: inline-block; margin-left: 67px;">
      <a href="mailto:shiml.madeline@gmail.com">shiml.madeline@gmail.com</a>
    </span>
    <br>

    GitHub:
    <a href="https://github.com/MadelineShi">MadelineShi</a>
    <br>

    LinkedIn
    <a href="https://www.linkedin.com/in/manlin-shi-965621310/"MadelineShi</a>
    <br>

    <a href="/Madeline_Shi_CV.pdf">CV</a>
  </p>

  <br>

  <p>
    <strong>News</strong>
  </p>

  <p>
    <small>
      2026.08 Completed a summer research internship at the Shenzhen Institute of Computing Sciences.
    </small>
  </p>

theme: jekyll-theme-minimal
show_downloads: false
